# introduction to Numpy

In [40]:
import numpy as np 
import array

In [41]:
b= array.array('i',[1,3,4,5,6,7,8])
b

array('i', [1, 3, 4, 5, 6, 7, 8])

In [ ]:
type(b) # type of array 

array.array

In [42]:
a=np.array([[1,2,4],
            [4,5,6]])
print(a.shape)
print(a)

(2, 3)
[[1 2 4]
 [4 5 6]]


In [75]:
type(a)

numpy.ndarray

In [76]:
a.dtype

dtype('int64')

In [43]:
c=np.arange(9)  #  1 dim
print(c)

[0 1 2 3 4 5 6 7 8]


In [77]:
type(c)

numpy.ndarray

In [78]:
c.dtype

dtype('int64')

In [44]:
c.shape

(9,)

In [45]:
d=c[np.newaxis,:] # 2 dim
print(d)

[[0 1 2 3 4 5 6 7 8]]


In [46]:
d.shape

(1, 9)

In [47]:
e=c[:,np.newaxis]
print(e)

[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]]


In [48]:
e.shape

(9, 1)

In [49]:
f=d[np.newaxis,:] # 3 dim
print(f)

[[[0 1 2 3 4 5 6 7 8]]]


# use of dimensions
### why we use 1D, 2D, 3D arrays use and when ?? and where to need them in data scinece

### 🌟 Where Do We Need Them in Data Science?
Dimension	Use Case in Data Science
1D Array	Feature vectors, time series analysis, stock market data
2D Array	Datasets, matrices, image processing, recommendation systems
3D Array	Deep learning, video processing, medical image analysis


# Summary
🔹 1D Arrays: Simple lists, time-series, single-variable data
🔹 2D Arrays: Tables, datasets, image processing
🔹 3D Arrays: RGB images, video frames, deep learning tensors



# creating arrays with NUMPY


In [56]:
a1= np.array([1,34,5,6,78,45])
a2= np.array([[45,67,78,89,6,9], [3,7,8,5,9,0]])



In [59]:
print(a1)
a1.shape

[ 1 34  5  6 78 45]


(6,)

In [58]:
print(a2)
a2.shape

[[45 67 78 89  6  9]
 [ 3  7  8  5  9  0]]


(2, 6)

# Initalize array 

In [ ]:
zeros= np.zeros((3,4))  # (rows, columns)
zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [71]:
zeros.dtype

dtype('float64')

In [ ]:
ones=np.ones((3,4))   # for ones
ones 

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [70]:
ones.dtype

dtype('float64')

In [ ]:
full= np.full((4,6),5)  # full the array with 5 
full

array([[5, 5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5, 5]])

In [69]:
full.dtype

dtype('int64')

In [67]:
# identity Matrix 
identity= np.eye(5) # numpy create identiy matirix 
identity

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [68]:
identity.dtype

dtype('float64')

# Attributes of arrays 

In [ ]:
a.shape # about matrix rows and columns 

(2, 3)

In [ ]:
len(identity) # finding length of arrray

5

In [84]:
full.ndim  # give dimension of array 

2

In [85]:
identity.ndim

2

In [ ]:
ones.size  # no of elements in array (total elements )

12

In [88]:
full.size

24

# Basic operation of arrays 

In [ ]:
g=a1-a2 # subtraction 
g

array([[-44, -33, -73, -83,  72,  36],
       [ -2,  27,  -3,   1,  69,  45]])

In [92]:
# addition of elements
h=a1+a2
h

array([[ 46, 101,  83,  95,  84,  54],
       [  4,  41,  13,  11,  87,  45]])

In [93]:
# an other method of addition 
h1=np.add(a1, a2)
h1

array([[ 46, 101,  83,  95,  84,  54],
       [  4,  41,  13,  11,  87,  45]])

In [95]:
# multiplications 
i=a1*a2
i

array([[  45, 2278,  390,  534,  468,  405],
       [   3,  238,   40,   30,  702,    0]])

In [96]:
# division 
j=a1/a2
j


C:\Users\aqso\AppData\Local\Temp\ipykernel_14564\1121527815.py:2: RuntimeWarning: divide by zero encountered in divide
  j=a1/a2


array([[ 0.02222222,  0.50746269,  0.06410256,  0.06741573, 13.        ,
         5.        ],
       [ 0.33333333,  4.85714286,  0.625     ,  1.2       ,  8.66666667,
                inf]])

In [97]:
# square of each element 
k= ones**2
k

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [98]:
k1= full**2
k1

array([[25, 25, 25, 25, 25, 25],
       [25, 25, 25, 25, 25, 25],
       [25, 25, 25, 25, 25, 25],
       [25, 25, 25, 25, 25, 25]])