# NUMPY indexing and silicing 

In [22]:
import numpy as np 

In [23]:
# create an array 
a= np.array([1,2,3,4,5,6,7,8])
a

array([1, 2, 3, 4, 5, 6, 7, 8])

In [24]:
a[0]

np.int64(1)

In [25]:
a[0:]

array([1, 2, 3, 4, 5, 6, 7, 8])

In [26]:
a[0:3]

array([1, 2, 3])

In [27]:
a[-1]

np.int64(8)

In [28]:
a[-2]

np.int64(7)

In [29]:
b= np.arange(0,12,2)
b

array([ 0,  2,  4,  6,  8, 10])

In [30]:
b[2]

np.int64(4)

In [31]:
c=b.reshape(2,3)
c

array([[ 0,  2,  4],
       [ 6,  8, 10]])

In [32]:
c[0]

array([0, 2, 4])

In [33]:
c[c<5]

array([0, 2, 4])

In [34]:
c[c%2==0]

array([ 0,  2,  4,  6,  8, 10])

# Elist boolen operator and conditional operators 
##### making the array for existing data 

In [35]:
a= np.arange(0,222,5)
a

array([  0,   5,  10,  15,  20,  25,  30,  35,  40,  45,  50,  55,  60,
        65,  70,  75,  80,  85,  90,  95, 100, 105, 110, 115, 120, 125,
       130, 135, 140, 145, 150, 155, 160, 165, 170, 175, 180, 185, 190,
       195, 200, 205, 210, 215, 220])

In [36]:
len(a)

45

In [37]:
arr_1= a[40:45]

In [38]:
arr_1

array([200, 205, 210, 215, 220])

In [39]:
a= np.array([1,3,4,5,6,7,8,])
b=np.array([9,2,4,77,22, 21,34])

In [40]:
# vertical stack 
c=np.vstack((a,b))
c

array([[ 1,  3,  4,  5,  6,  7,  8],
       [ 9,  2,  4, 77, 22, 21, 34]])

In [ ]:
# horizontal stack 
d=np.hstack((a,b))
d

array([ 1,  3,  4,  5,  6,  7,  8,  9,  2,  4, 77, 22, 21, 34])

In [43]:
d.reshape(2,7)

array([[ 1,  3,  4,  5,  6,  7,  8],
       [ 9,  2,  4, 77, 22, 21, 34]])

In [44]:
d.reshape(7,2)

array([[ 1,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [ 2,  4],
       [77, 22],
       [21, 34]])