# NUMPY(day_2)

In [87]:
import numpy as np

In [88]:
# empty array 
empty= np.empty((2,3))
empty

array([[1.680e-322, 2.767e-322, 2.964e-323],
       [3.844e-321, 4.397e-322, 1.680e-322]])

In [89]:
print(empty[0])
print(empty[1])

[1.68e-322 2.77e-322 2.96e-323]
[3.844e-321 4.397e-322 1.680e-322]


In [90]:
# array of even _ numbers 
a=np.arange(2,9,2)  # here 2 means start , 9 means end , 2 spaces 
a

array([2, 4, 6, 8])

In [91]:
# array of odd _NUmbers 
b= np.arange(1,10,2)
b

array([1, 3, 5, 7, 9])

In [92]:
# linspace (linear space )
lin= np.linspace(0,10,num=5) # linearly work 
lin

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [93]:
x= np.arange(6)
x

array([0, 1, 2, 3, 4, 5])

In [94]:
z = x.reshape(3,2)
z

array([[0, 1],
       [2, 3],
       [4, 5]])

In [95]:
# we can tell the data type of array 
lin.dtype

dtype('float64')

In [96]:
# define the data type of array 
s = np.ones(2,dtype=np.int64)
s

array([1, 1])

# **Assignment** (what is differnece between int64, int32, float64 , and int32 , int128, int8)
# why we use ?? 
####### Assignment:The terms you mentioned, such as int32, int64, float32, float64, and float16, are data types commonly used in programming languages to represent different kinds of numerical values. Here's a brief explanation of each data type: Int32 (or int): It stands for a 32-bit signed integer. The "int" data type is used to store whole numbers (positive, negative, or zero) without any fractional parts. The 32-bit refers to the number of bits used to represent the value, which determines the range of numbers that can be stored. In the case of int32, it can store values from approximately -2 billion to +2 billion. Int64 (or long): It stands for a 64-bit signed integer. Similar to int32, it represents whole numbers, but with a larger range. The 64-bit representation allows for much larger integer values to be stored, ranging from approximately -9 quintillion to +9 quintillion. Float32 (or float): It stands for a 32-bit floating-point number. Floating-point numbers are used to represent real numbers (numbers with fractional parts). The 32-bit representation allows for a certain level of precision but with a limited range. Float32 can represent numbers with about 7 decimal digits of precision. Float64 (or double): It stands for a 64-bit floating-point number. Similar to float32, but with a larger range and higher precision. Float64 can represent numbers with about 15 decimal digits of precision. Float16: It stands for a 16-bit floating-point number. It has a smaller range and precision compared to float32 and float64. Float16 is commonly used in applications where memory usage is critical, such as in machine learning models running on specialized hardware.

# sorting of numpy


In [97]:
arr= np.array([3,5,2,4,6,67,7,4,344,56])
arr

array([  3,   5,   2,   4,   6,  67,   7,   4, 344,  56])

In [98]:
arr=np.sort(arr)  #  this is sorted element 
arr

array([  2,   3,   4,   4,   5,   6,   7,  56,  67, 344])

In [99]:
# concatenate the array of 1 dimension array 
r= np.array([34,56,6,778,89,34])
d=np.array([21,67,8,9,32,90])


In [100]:
t= np.concatenate((r,d))
t

array([ 34,  56,   6, 778,  89,  34,  21,  67,   8,   9,  32,  90])

In [101]:
# concatenate the array of 2d array 
a1= np.array([[12,45],[11,55]])
b1=np.array([[45,78]])


In [102]:
# concatenate of 2d array 
c1=np.concatenate((a1,b1))
c1

array([[12, 45],
       [11, 55],
       [45, 78]])

In [103]:
z= np.concatenate((a1,b1),axis=0) #  concate the array at axis 0 (put at below the array )
z

array([[12, 45],
       [11, 55],
       [45, 78]])

In [104]:
w= np.array([[2,3],[1,3]])
e= np.array([[4,6],[7,8]])


In [105]:
r1=np.concatenate((w,e),axis=1) # concate tahe array at axis 1  (put the array at side of the array )
r1

array([[2, 3, 4, 6],
       [1, 3, 7, 8]])

In [106]:
w.ndim

2

# 3D dimenison array 

In [107]:
arr_2= np.array([[[1,3,4,5],[7,8,9,3]],
                 [[54,6,77,89],[34,21,45,34]],
                 [[56,45,78,90],[23,1,2,45]]])
arr_2

array([[[ 1,  3,  4,  5],
        [ 7,  8,  9,  3]],

       [[54,  6, 77, 89],
        [34, 21, 45, 34]],

       [[56, 45, 78, 90],
        [23,  1,  2, 45]]])

In [108]:
len(arr_2)

3

In [109]:
arr_2.ndim

3

In [110]:
arr_2.size

24

In [111]:
arr_2.shape

(3, 2, 4)

In [112]:
#create the 3D array 
d= np.array([[[1,3,4,5]],
             [[7,8,9,0]],
             [[1,2,8,7]]])
d.shape


(3, 1, 4)

In [113]:
d.ndim

3

In [114]:
r= d.reshape(6,2)
r

array([[1, 3],
       [4, 5],
       [7, 8],
       [9, 0],
       [1, 2],
       [8, 7]])

In [115]:
r1=d.reshape(3,2,2)
r1

array([[[1, 3],
        [4, 5]],

       [[7, 8],
        [9, 0]],

       [[1, 2],
        [8, 7]]])

In [122]:
# make a 1D array  and converted in to 2D array 
a = np.array([1, 2, 3, 4, 5, 6])
a.shape

(6,)

In [127]:
a2 = a[np.newaxis, :]
a2.shape


(1, 6)

In [128]:
a2

array([[1, 2, 3, 4, 5, 6]])

In [129]:
col_vector = a[:, np.newaxis]
col_vector.shape

(6, 1)

In [130]:
col_vector

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

# indexing and silicing 


In [131]:
x1= np.array([1,2,3,4,5,6,7,8])
x1

array([1, 2, 3, 4, 5, 6, 7, 8])

In [133]:
x1[2:5]

array([3, 4, 5])

In [ ]:
x1[: : -1]  # reverse array 

array([8, 7, 6, 5, 4, 3, 2, 1])

# indexing and silicing in 2D array 

In [139]:
y=np.array([[1,2,4,3],[5,6,7,8],[9,0,5,3]])
y

array([[1, 2, 4, 3],
       [5, 6, 7, 8],
       [9, 0, 5, 3]])

In [140]:
y[0]

array([1, 2, 4, 3])

In [142]:
y[0][1:3]

array([2, 4])

In [143]:
y[2][::-1]

array([3, 5, 0, 9])

In [144]:
y[1][2:]

array([7, 8])

In [145]:
y[y<5]

array([1, 2, 4, 3, 0, 3])

In [146]:
y[y<2]

array([1, 0])

In [147]:
y[y>10]

array([], dtype=int64)

In [148]:
y[y<=10]

array([1, 2, 4, 3, 5, 6, 7, 8, 9, 0, 5, 3])

In [ ]:
#FILTER THE ODD NUMBERS 
b[b % 2 == 1]

array([1, 3, 5, 7, 9])

In [158]:
# CONDTINAL OPERATOR 
b[(b>2) & (b<11) & (b %2 == 1)]

array([3, 5, 7, 9])

In [160]:
b[(b>2)|(b<11)]
print(b)

[1 3 5 7 9]
