# Matrix or Matrices 

In [2]:
import numpy as np 


In [3]:
#create the 2*3 matrix
a= np.array([[1,2,3,4], [5,6,7,8]])
a

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [4]:
# create a matrix of big dimension 
b= np.arange(0,100,2)
b

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66,
       68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [5]:
b= np.arange(0,100,2).reshape(5,10)
b

array([[ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28, 30, 32, 34, 36, 38],
       [40, 42, 44, 46, 48, 50, 52, 54, 56, 58],
       [60, 62, 64, 66, 68, 70, 72, 74, 76, 78],
       [80, 82, 84, 86, 88, 90, 92, 94, 96, 98]])

In [6]:
b= np.arange(0,100,2).reshape(10,5) # reshape the array into matrix 
b

array([[ 0,  2,  4,  6,  8],
       [10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28],
       [30, 32, 34, 36, 38],
       [40, 42, 44, 46, 48],
       [50, 52, 54, 56, 58],
       [60, 62, 64, 66, 68],
       [70, 72, 74, 76, 78],
       [80, 82, 84, 86, 88],
       [90, 92, 94, 96, 98]])

In [7]:
b= np.arange(0,100,2).reshape(5,10)
b

array([[ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28, 30, 32, 34, 36, 38],
       [40, 42, 44, 46, 48, 50, 52, 54, 56, 58],
       [60, 62, 64, 66, 68, 70, 72, 74, 76, 78],
       [80, 82, 84, 86, 88, 90, 92, 94, 96, 98]])

In [8]:
# silicig a matrix 
b[1:3 ,3:5]

array([[26, 28],
       [46, 48]])

In [9]:
b[0: , 5 :8]

array([[10, 12, 14],
       [30, 32, 34],
       [50, 52, 54],
       [70, 72, 74],
       [90, 92, 94]])

# axis 0 for rows and axis 1 for columns  


# Axis	Operation Direction	Example
## axis=0	Column-wise (↓)	np.sum(a, axis=0) sums vertically (column-wise)
## axis=1	Row-wise (→)	np.sum(a, axis=1) sums horizontally (row-wise)
## So, axis=0 is for columns, and axis=1 is for rows (opposite of what you initially thought).

In [10]:
b.max()

np.int64(98)

In [11]:
b.min()

np.int64(0)

In [12]:
b.sum()

np.int64(2450)

In [13]:
b.max(axis=0) # for columns 

array([80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [14]:
b.min(axis=0)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [15]:
b.min(axis=1)

array([ 0, 20, 40, 60, 80])

In [16]:
b.max(axis=1) #  this is only for rows 

array([18, 38, 58, 78, 98])

In [17]:
b


array([[ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28, 30, 32, 34, 36, 38],
       [40, 42, 44, 46, 48, 50, 52, 54, 56, 58],
       [60, 62, 64, 66, 68, 70, 72, 74, 76, 78],
       [80, 82, 84, 86, 88, 90, 92, 94, 96, 98]])

In [18]:
b.max(axis=0) # only for columns 

array([80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [19]:
m= np.arange(0,20,2).reshape(5,2)
m

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10],
       [12, 14],
       [16, 18]])

In [20]:
# plus the whole array with new array 
m+np.array([20,10])

array([[20, 12],
       [24, 16],
       [28, 20],
       [32, 24],
       [36, 28]])

##### if we add  the new row and columns already existing matrix  then we use the v_stack and H_stack 


In [21]:
# using v stack 
np.vstack((m,np.array([42,44])))

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10],
       [12, 14],
       [16, 18],
       [42, 44]])

In [22]:
m

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10],
       [12, 14],
       [16, 18]])

In [ ]:
# for h_stack (adding columns )
np.hstack((m, np.array([[42], [44], [46], [48], [50]])))

array([[ 0,  2, 42],
       [ 4,  6, 44],
       [ 8, 10, 46],
       [12, 14, 48],
       [16, 18, 50]])

In [ ]:
b

array([[ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28, 30, 32, 34, 36, 38],
       [40, 42, 44, 46, 48, 50, 52, 54, 56, 58],
       [60, 62, 64, 66, 68, 70, 72, 74, 76, 78],
       [80, 82, 84, 86, 88, 90, 92, 94, 96, 98]])

In [ ]:
np.flip(b) # resverse the whole matrix 

array([[98, 96, 94, 92, 90, 88, 86, 84, 82, 80],
       [78, 76, 74, 72, 70, 68, 66, 64, 62, 60],
       [58, 56, 54, 52, 50, 48, 46, 44, 42, 40],
       [38, 36, 34, 32, 30, 28, 26, 24, 22, 20],
       [18, 16, 14, 12, 10,  8,  6,  4,  2,  0]])

TypeError: array() takes from 1 to 2 positional arguments but 6 were given